Form changes
aggie-coding-club/club-website pull request #139
Opened 2020-02-29 22:53 UTC by daks001

2020-02-29 23:04 UTC, SaltyQuetzals requested changes

2020-02-29 23:04 UTC, SaltyQuetzals commented on src/views/about.html
>      <title>Aggie Coding Club - About</title>
```suggestion
    <meta charset="UTF-8">
    <title>Aggie Coding Club - About</title>
```
We only need it one time

2020-02-29 23:29 UTC, SaltyQuetzals approved these changes

2020-02-29 23:30 UTC, merged

2020-03-01 00:19 UTC, daks001 commented
#closes 137

2020-03-01 00:20 UTC, daks001 commented
closes #137